before_script:
  - export PATH=~/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
  - apt-get update
  - apt-get install -y git-annex
  - gem install --bindir /usr/local/bin bundler
  - cp config.yml.example config.yml
  - bundle install

rspec:
  script:
    - bundle exec rspec spec
  tags:
    - ruby
  except:
    - tags

rubocop:
  script: 
    - bundle exec rubocop
  tags:
    - ruby
  except:
    - tags
