#!/usr/bin/env ruby

# This file was placed here by GitLab. It makes sure that your pushed commits
# will be processed properly.

refs = $stdin.read
key_id  = ENV.delete('GL_ID')
repo_path = Dir.pwd

require_relative '/opt/gitlab/embedded/service/gitlab-shell/lib/gitlab_custom_hook'
require_relative '/opt/gitlab/embedded/service/gitlab-shell/lib/gitlab_post_receive'

if GitlabPostReceive.new(repo_path, key_id, refs).exec &&
    GitlabCustomHook.new.post_receive(refs, repo_path)
  exit 0
else
  exit 1
end
